version: '3.8'

# https://github.com/wurstmeister/kafka-docker
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    build: .
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - $PWD/kafka/docker.sock:/var/run/docker.sock
